### ISSUE TITLE
Distribute configure-repositories as a CLI

### ISSUE THREAD

**Issue by eliflores** [serlo/configure-repositories#3]
As a developer, I would like `configure-repositories` to be distributed as a CLI that I can download directly from the [releases](https://github.com/serlo/configure-repositories/releases) of the repository. 

This way in my Dev machine, I can install it with:
```
pip install git+https://github.com/serlo/configure-repositories@RELEASE_TAG
```

and I don't need to clone the repository, or know about the internal scripts that exist in the code base, and I only need to run it as: `configure-repositories --help`.

**Comment by hugotiburtino** [comment]
I always loved the idea of a CLI 😉 

Minor pool:
What about naming it?
- `serlo`
- `srl`
- `yolo`
- `lama`

Just kidding: each person can create an alias as they like it 😄

**Comment by eliflores** [comment]
Distributed as a binary in https://github.com/serlo/configure-repositories/pull/19.
